export const BOOKS = [
  {
    id: 1,
    title: 'Cien Años de Soledad',
    author: 'Gabriel García Márquez',
    price: 18.99,
    originalPrice: 24.99,
    cover: '/img/CienAñosDeSoledad.webp',
    category: 'Literatura',
    rating: 4.9,
    reviews: 2341,
    stock: 12,
    description: 'La obra maestra del realismo mágico. La saga de la familia Buendía en el mítico pueblo de Macondo.',
    tags: ['Clásico', 'Realismo Mágico', 'Nobel'],
    featured: true,
  },
  {
    id: 2,
    title: 'Lo que no tiene nombre',
    author: 'piedad Bonet',
    price: 16.5,
    originalPrice: 21.0,
    cover: '/img/piedadbonet-notienenombre.webp',
    category: 'Fantasía',
    rating: 4.8,
    reviews: 1892,
    stock: 8,
    description: '',
    tags: ['Fantasía épica', 'Magia', 'Aventura'],
    featured: true,
  },
  {
    id: 3,
    title: 'Metamorfosis',
    author: 'Franz kafka',
    price: 12.99,
    originalPrice: 15.99,
    cover:'/img/metamorfosis.webp',
    category: 'Distopía',
    rating: 4.7,
    reviews: 3102,
    stock: 20,
    description: 'Un inquietante retrato de un estado totalitario donde el Gran Hermano lo controla todo.',
    tags: ['Clásico', 'Política', 'Ciencia ficción'],
    featured: false,
  },
  {
    id: 4,
    title: '1984',
    author: 'George Orwell',
    price: 22.0,
    originalPrice: 28.0,
    cover: '/img/1984george.webp',
    category: 'Distopía',
    rating: 4.8,
    reviews: 2780,
    stock: 5,
    description: 'La épica historia de Paul Atreides en el planeta desierto de Arrakis, fuente de la especia más valiosa del universo.',
    tags: ['Épico', 'Política', 'Ecología'],
    featured: false,
  },
  {
    id: 5,
    title: 'El Principito',
    author: 'Antoine de Saint-Exupéry',
    price: 9.99,
    originalPrice: 12.0,
    cover: '/img/ElPrincipito.jpg',
    category: 'Literatura',
    rating: 4.9,
    reviews: 4521,
    stock: 30,
    description: 'Un cuento poético y filosófico con significados más profundos sobre la vida y las relaciones humanas.',
    tags: ['Clásico', 'Infantil', 'Filosofía'],
    featured: false,
  },
  {
    id: 6,
    title: 'El extranjero',
    author: 'Albert Camus',
    price: 19.99,
    originalPrice: 25.0,
    cover: '/img/Elextranjero.webp',
    category: 'No Ficción',
    rating: 4.6,
    reviews: 1654,
    stock: 15,
    description: 'El extranjero" (1942) de Albert Camus narra la historia de Meursault, un oficinista argelino apático e indiferente, que mata a un árabe en una playa tras el funeral de su madre. Dividida en dos partes, la novela explora el absurdo de la existencia a través de un juicio donde Meursault es condenado, no tanto por el crimen, sino por su falta de emociones sociales.',
    tags: ['Historia', 'Antropología', 'Bestseller'],
    featured: true,
  },
  {
    id: 7,
    title: 'Noches Blancas',
    author: 'Fiódor M. Dostoievski',
    price: 15.5,
    originalPrice: 20.0,
    cover: '/img/NochesBlancas.webp',
    category: 'Misterio',
    rating: 4.7,
    reviews: 1234,
    stock: 9,
    description: '"Noches blancas" de Fiódor Dostoievski es una novela sentimental que narra, a lo largo de cuatro noches en San Petersburgo, la historia de un joven soñador y solitario que conoce a Nástenka, una joven de la que se enamora. Ella, a la espera de su verdadero amor, busca consuelo en él, resultando en un efímero romance de verano. ',
    tags: ['Misterio', 'Barcelona', 'Drama'],
    featured: false,
  },
  {
    id: 8,
    title: 'Harry Potter y la Piedra Filosofal',
    author: 'J.K. Rowling',
    price: 14.99,
    originalPrice: 18.0,
    cover: '/img/HarryPotterPiedraFilosofal.webp',
    category: 'Fantasía',
    rating: 4.9,
    reviews: 5678,
    stock: 25,
    description: 'El inicio de la saga más vendida de la historia. Un niño descubre que es un mago.',
    tags: ['Magia', 'Aventura', 'Infantil'],
    featured: false,
  },
]

export const CATEGORIES = ['Todos', 'Literatura', 'Fantasía', 'Ciencia Ficción', 'No Ficción', 'Misterio', 'Distopía']